import React from "react";
import "../css/About.css";

const About = () => {
  return (
    <div className="about-page">
      <h1>About Us</h1>
      <p>Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.Welcome to my portfolio! I am a passionate developer dedicated to building impactful solutions.</p>
    </div>
  );
};

export default About;